/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zavier_androidfunctiontestv2_usbCommunication_hid_OpenUsbHidPort */

#ifndef _Included_com_zavier_androidfunctiontestv2_usbCommunication_hid_OpenUsbHidPort
#define _Included_com_zavier_androidfunctiontestv2_usbCommunication_hid_OpenUsbHidPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zavier_androidfunctiontestv2_usbCommunication_hid_OpenUsbHidPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_zavier_androidfunctiontestv2_usbCommunication_hid_OpenUsbHidPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_zavier_androidfunctiontestv2_usbCommunication_hid_OpenUsbHidPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zavier_androidfunctiontestv2_usbCommunication_hid_OpenUsbHidPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
