/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort */

#ifndef _Included_com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort
#define _Included_com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort
 * Method:    close
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort_close
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort
 * Method:    read
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort_read
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort
 * Method:    write
 * Signature: (Ljava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_com_zavier_androidfunctiontestv2_SerialPortTest_SerialPort_write
  (JNIEnv *, jobject, jstring, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
